### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by denolfe** [dlrudie/Snip#17]
Hello, Snip is crashing on launch for me on Windows 8 without any error messages. I am not getting this crash on my Windows 7 machine.  Let me know if I can provide any other information.

This is the output for me in Event Viewer:

```
Application: Snip.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at Winter.KeyboardHook.RegisterHotkey(Winter.ModifierHookKeys, System.Windows.Forms.Keys)
   at Winter.Snip..ctor()
   at Winter.Program.Main()
```

**Comment by nathanhosselton** [comment]
Thought I would mention that my Snip was crashing immediately with similar Event Viewer errors as the OP and running the alternative version provided a couple of posts up works fine, so I may also be experiencing the hotkey issue even with the latest version.

**Comment by nathanhosselton** [comment]
Nevermind. It worked the first time I launched it but wasn't writing the text file so I restarted it and now it crashes in the same manner as before. Not sure what to do. For reference, the Event Viewer logs for 5.3.1.0 are below.

```
Application: Snip.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Resources.MissingManifestResourceException
   at System.Resources.FileBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at System.Resources.ResourceManager.GetString(System.String)
   at Winter.Snip..ctor()
   at Winter.Program.Main()
```
```
Faulting application name: Snip.exe, version: 5.3.1.0, time stamp: 0x56fc993b
Faulting module name: KERNELBASE.dll, version: 10.0.10586.306, time stamp: 0x571afb9a
Exception code: 0xe0434352
Fault offset: 0x000bdae8
Faulting process id: 0x1570
Faulting application start time: 0x01d1af8f50fb9edb
Faulting application path: C:\Users\RYZ3R\Desktop\Snip.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: 70c6271b-24b0-43cc-bd3c-ae9def23e63f
Faulting package full name: 
Faulting package-relative application ID: 
```
