### ISSUE TITLE
'Spotify is not currently running'

### ISSUE THREAD

**Issue by microkorg** [dlrudie/Snip#265]
Snip used to work very reliably until perhaps two weeks ago.
Now it intermittently decides whether or not to detect songs.
Sometimes a song will change and it will pick it up, and then mid-song just switch to "Spotify is not currently running."
I'd say around 5-10% of the time it detects a song, and the rest of the time it does not.

_Things I've tried:_
- Reinstalling snip (the last few versions and the most recent.)
- Clearing the snip registry settings.
- Reinstalling spotify.
- Changing as many spotify settings as I can possibly try.

**Comment by RealSebubu** [comment]
I've run into the same problem.
I've have reinstalled Spotify and Snip.
I checked whether spotify web helper was running, it was.

It seems to be succesful for around half the song then it removes the text. If you hover your mouse over Snip in the system tray it says 'Spotify is not currently running'. 

Thanks for the help in advance :D

**Comment by microkorg** [comment]
Yup, done all of the above, hasn't change a thing.
Occasionally if I restart my PC I'll get it working for a half dozen songs, but then it quits.

**Comment by microkorg** [comment]
I'm almost completely sure it's the most recent version of Spotify that broke it. _(1.0.77.338)_  But as far as I can tell there is no way to downgrade your spotify, as even if you could, it automatically updates.

**Comment by GenesisFR** [comment]
I've been banging my head for 2 days on this issue. I tried running stock 6.9.5 and 6.9.1 from Visual Studio and the JSON returned from the "https://api.spotify.com/v1/tracks/" endpoint is always null. It used to work, not anymore :(.

**Comment by itzm4x1mu5** [comment]
I've Downloaded the latest update snip and its working fine for me 
[https://github.com/dlrudie/Snip](url)

**Comment by RealSebubu** [comment]
It seems to have something to do with spotify speakers. Cause when I turned mine off it worked fine. 🤔

**Comment by GenesisFR** [comment]
Any update on this issue @dlrudie? I have a few things I'd like to implement in Snip but this issue is a total blocker for me.

The released version of 6.9.5 seems to work fine but when compiling the source, it doesn't.

**Comment by dlrudie** [comment]
It probably doesn't work for you when compiling because you'll need your own API key.

**Comment by GenesisFR** [comment]
I do have my own API key, I even regenerated my secret and recreated a new app on https://beta.developer.spotify.com just to make sure my API key wasn't the problem, to no avail.

**Comment by dlrudie** [comment]
So what's the problem when compiling? There's not enough detail here.

**Comment by GenesisFR** [comment]
It compiles, I described the problem earlier https://github.com/dlrudie/Snip/issues/265#issuecomment-379264288

**Comment by dlrudie** [comment]
I couldn't say at all then. If you have a good key then it should work.

For your key, make a file called ApplicationKeys.cs

Add the following code:

```
namespace Winter
{
    public static class ApplicationKeys
    {
        public const string Spotify = "YOURKEY";
    }
}
```

**Comment by GenesisFR** [comment]
I already did, here's my ApplicationKeys.cs:

```
public static class ApplicationKeys
{
    public static string clientid = "";
    public static string clientsecret = "";
    public static string Spotify = Convert.ToBase64String(Encoding.UTF8.GetBytes(string.Format("{0}:{1}", clientid, clientsecret)));
}
```

I removed my credentials on purpose.

**Comment by dlrudie** [comment]
Just add a messagebox that pops up with the JSON to see if it's actually getting any kind of result.

**Comment by GenesisFR** [comment]
![image](https://user-images.githubusercontent.com/3614449/38460801-5f5e3d7e-3a8f-11e8-8476-3785a4810f48.png)

If you have some spare time, is there any place where we could take this issue further? I don't want to monopolize this thread with my issue. I can show you what happens on twitch if you want (link on my profile).

**Comment by dlrudie** [comment]
What if you show the trackId? Make sure trackId is not empty, which means the JSON further above it can't be empty either.

**Comment by dlrudie** [comment]
Make sure cache metadata isn't enabled. If possibly you downloaded a blank json file and it stored it as metadata then it's going to have nothing in it.

Try commenting out the cache metadata part of it and see if it works.

**Comment by GenesisFR** [comment]
Disabled cache metadata, tried with this:

```
string json = string.Empty;

//if (Globals.CacheSpotifyMetadata)
{
    json = this.ReadCachedJson(trackId);
}
//else
{
    json = this.DownloadJson(
        string.Format(
            CultureInfo.InvariantCulture,
            "https://api.spotify.com/v1/tracks/{0}",
            trackId),
        SpotifyAddressContactType.API);
}
```

The value of json is empty in both cases, it never creates any JSON file in the SpotifyMetadata folder while enabling cache metadata. It does work on the 6.9.5 release I downloaded from GitHub.

**Comment by dlrudie** [comment]
The only thing I can really think of is that it's an endpoint issue for you. Maybe the token is not right or the API key is not right.

Dig further back into the token request code and see if you're indeed getting a valid token.

**Comment by GenesisFR** [comment]
Turned out my secret key was incorrect, thanks for your time.

**Comment by ImSkiZzy** [comment]
any fix?

**Comment by GenesisFR** [comment]
Local file support should be added in the next release according to #465ed54

**Comment by triedthisonline** [comment]
Hopefully this isn't too old of a post to add on to this issue. 

I've noticed that my Snip stops working and shows "Spotify is not currently running." only when I launch a game or game service like Steam/Battle.net/Origin. I'm not sure if this is related to what everyone else in this thread is experiencing, at first it looked to me like it would just glitch out randomly but after messing around with my OBS overlay for hours today the connection was obvious.

I'm using the latest version of Spotify (1.0.80.474.gef6b503e) and am on Windows 10 if that makes any difference. I'm using Streamlabs OBS to stream on Twitch.

**Comment by GenesisFR** [comment]
Spotify uses CEF, and the way Snip uses to find the Spotify window handle is not entirely reliable. I actually wrote a [gist](https://gist.github.com/GenesisFR/de0ad5710fb5eb221b5a239e819728bf) a while ago to avoid this kind of problem.

While I've had no issue with Discord and Steam on Win10, running these [applications](https://en.wikipedia.org/wiki/Chromium_Embedded_Framework#Applications_using_CEF) before Spotify and Snip may prevent the correct window handle from being found.

Try to close everything, run Spotify, then Snip, then the other apps and see if it works.

**Comment by triedthisonline** [comment]
Thanks for responding, GenesisFR.

I tried turning everything off, starting Steam -> OBS -> Spotify -> Snip and it didn't work. Then I decided, what fixes everything? **I restarted my computer**, this time I loaded both Steam and Battle.net, then OBS -> Spotify -> Snip and **it did work**. I opened a bunch of different games all while keeping the launchers open and haven't encountered an issue yet. I'll be testing more later today and if I notice this program sequence not working in the future I'll post an update. Thanks again! 🙂

**Comment by Position1** [comment]
Hi, Im having the exact same problem while trying to install this. I installed snip perfectly but then ended up not working and currently saying "Spotify is not running" when it clearly is. And the text file is completely empty while i am playing a track.

I also have no other applications open other than OBS, Spotify, snip and chrome.
Any help is appreciated

**Comment by peerluk** [comment]
Same problem here. Any help would be appreciated.
Thanks

**Comment by pswaab** [comment]
Hi,

Any news yet? I updated from 6.9.1 to 6.9.5 but that doesn't work.
I use the windows executable only.
How does the compile work? And where should I place a spotify api key/secret?

Hope someone can help me out.

Kind regards,

Patrick Swaab

**Comment by GenesisFR** [comment]
@pswaab https://github.com/dlrudie/Snip/issues/299#issuecomment-406359335

**Comment by markspolakovs** [comment]
I've added in some logging, and here's what I get:

```
2018-07-20 15:51:36 [EXCEPTION]: Unable to connect to the remote server

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Winter.Spotify.DownloadJson(String jsonAddress, SpotifyAddressContactType spotifyAddressContactType) in C:\Code\Snip\Snip\Players\Spotify.cs:line 574
```

**Comment by markspolakovs** [comment]
what the fuck?

This is the OAuth token that Spotify gives me (slightly modified): `NAowChgKB1Nwb3RpZnkSABoAAAAAAAAAAAAAAAAAfaketoken`

why the fuck is there `faketoken`?

See https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/134 - I think it's trying to stop non-Spotify clients from using the local API

**Comment by TheSqrtMinus1** [comment]
also getting this issue on newest spotify / newest snip
