### ISSUE TITLE
Error when launching 

### ISSUE THREAD

**Issue by MrRedxBeard** [dlrudie/Snip#27]
Getting this exception text - 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Winter.Spotify.Update()
   at Winter.Snip.TimerScanMediaPlayer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

http://i.imgur.com/xowsqUy.png 

I have tried running the software as administrator but when i launch spotify this error message pops up. 

install might have gone bad. when i first ran the application i did not have Spotify installed or running. Any suggestions will help.

**Comment by ygerupts** [comment]
yes I too am getting the same error.

**Comment by MrRedxBeard** [comment]
i found the cause, its because the newest version of spotify is not
compatible. you need to uninstall and reinstall an older version for it to
work.

**Comment by dlrudie** [comment]
Duplicate of #26.
