### ISSUE TITLE
Snip v6.10.0 Pre-Release Errors

### ISSUE THREAD

**Issue by mjgj96** [dlrudie/Snip#304]
Upon running the v6.10.0 pre-release for the first time, I received this Microsoft.NET Framework error: 

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Winter.Spotify.Unload()
   at Winter.Snip.ToggleSpotify()
   at Winter.Snip.PlayerSelectionCheck(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Snip
    Assembly Version: 6.10.0.0
    Win32 Version: 6.10.0.0
    CodeBase: file:///C:/Users/Michael/Google%20Drive/Mikey/Snip/Snip.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

When running the source code through Visual Studio, 'System.Net.WebException' in System.dll is thrown continuously until I re-selected the Spotify source (selecting any other source will also trigger this), resulting in this error:

![image](https://user-images.githubusercontent.com/19314369/43035605-fb4b1a6c-8cc0-11e8-8136-7d513e730f03.png)

By the way, I am using the ApplicationKeys.cs provided by GenesisFR in issue #299.

Sorry, I'm an über-noob when it comes to sharing this stuff, was trying to find a way to share more detailed results than a screenshot, but had no luck 😕 

Also, when attempting to run multiple instances of Snip, there are many errors concerning hotkeys already in use that pop up and feel a bit sloppy, for lack of a better word 😝

**Comment by neverbackdown81** [comment]
ii still cant get iit to work snip and spotify any idieas people still says spotify not running or track not playing

**Comment by mjgj96** [comment]
Be patient, @neverbackdown81, Spotify made a change to how their code works so it's going to take some time to fix. This is a side project for the developer so even though he gives it a lot of attention he still has a job and other things going on taking up his time.

**Comment by neverbackdown81** [comment]
genesisfr no im sorta noob how do i do this

**Comment by mjgj96** [comment]
Not in that screenshot @GenesisFR 🤦‍♂️ but once I did I received the same error, just without multiple "'System.Net.WebException' in System.dll" throws.

**Comment by TheSqrtMinus1** [comment]
running as an admin gets this to work for me, without throwing any errors. thanks for fixing it so fast, by the way!

**Comment by neverbackdown81** [comment]
@TheSqrtMinus1 it doesnt work for me through obs even when ran as admin

**Comment by murko69** [comment]
Just a notice. I also had this issue (no track) and updated to this new version, but still have the issue though.
Will try and re-install tomorrow and check, but so far no change from previous version(s)

**Comment by dlrudie** [comment]
So I completely forgot. The Unsafe methods I use require admin rights. I'll update Snip to request admin automatically when launching.
